version: '3.8'

services:
  ## POSTGRESQL ##
  postgres:
    container_name: postgres_db_security_demo
    image: postgres
    environment:
      POSTGRES_USER: dev-ninja
      POSTGRES_PASSWORD: ujac8ozJExiHFfcTNPd6
      POSTGRES_DB: security_demo
    ports:
      - "5432:5432"
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/'
    networks:
      - security_demo_net
    restart: always
  api:
    container_name: spring_api
    build: ./api/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - security_demo_net  
  web:
    container_name: next_web
    build: ./web/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - security_demo_net    

networks:
  security_demo_net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
